### ISSUE TITLE
Does it work on jetson xavier?

### ISSUE THREAD

**Issue by cy-goh** [jacobs-robotics/docker-camodocal#1]
Hi I am trying to get it to work on Nvidia Jetson Xavier, and I get the following error

```
Step 3/24 : RUN apt-get clean && apt-get update && apt-get install -y locales
 ---> Running in ec85cdcfc972
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c apt-get clean && apt-get update && apt-get install -y locales' returned a non-zero code: 1
```
Can I check with you if the failure is due to the container not being built for arm64?

**Comment by arturokkboss33** [comment]
Sorry for very late reply. Answering in case it is useful for others: Yes, the container uses the base image for x86-64 architectures. If it is needed for arm architectures, the base image in the Dockerfile needs to be changed, see please the nvidia/cuda-arm64 available images.
